files:
- generatedChecksum: 54D27D41EC009390E069CBCDA2B965BE
  logicalPath: config/pic32mx_125_sk/bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 54D27D41EC009390E069CBCDA2B965BE
- generatedChecksum: ED09B8AB240A0CBAB9D50F6BA7D3ADB0
  logicalPath: config/pic32mx_125_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED09B8AB240A0CBAB9D50F6BA7D3ADB0
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F6360A851EBD527779696BA43E05ADD2
  logicalPath: config/pic32mx_125_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F6360A851EBD527779696BA43E05ADD2
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mx_125_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config/pic32mx_125_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: 3A6AC185D95CF7B842B73952B02BA446
  logicalPath: config/pic32mx_125_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3A6AC185D95CF7B842B73952B02BA446
- generatedChecksum: 6BA90EB347ECD368824D77A76F44C819
  logicalPath: config/pic32mx_125_sk/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6BA90EB347ECD368824D77A76F44C819
- generatedChecksum: 5733E7E141B78CCE3D7F5714E6ACA902
  logicalPath: config/pic32mx_125_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5733E7E141B78CCE3D7F5714E6ACA902
- generatedChecksum: 678A5D88C0B4D56340890BE222A8EF42
  logicalPath: config/pic32mx_125_sk/bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 678A5D88C0B4D56340890BE222A8EF42
- generatedChecksum: A3E6E8BF58D0DE115264B2D9360D9D28
  logicalPath: config/pic32mx_125_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A3E6E8BF58D0DE115264B2D9360D9D28
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx_125_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx_125_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: FBB585EEB16EC8778351DF2A2A46884C
  logicalPath: config/pic32mx_125_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: FBB585EEB16EC8778351DF2A2A46884C
- generatedChecksum: 3D139289B450ACEE365DCF48273BA6C9
  logicalPath: config/pic32mx_125_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D139289B450ACEE365DCF48273BA6C9
- generatedChecksum: 96855F9531844D3DAC655F2F48350370
  logicalPath: config/pic32mx_125_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 96855F9531844D3DAC655F2F48350370
- generatedChecksum: FA9867071F47C3B47CB92F0D52B2D512
  logicalPath: config/pic32mx_125_sk/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: FA9867071F47C3B47CB92F0D52B2D512
- generatedChecksum: 316D6B34B34BF612D47E310073FD397D
  logicalPath: config/pic32mx_125_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 316D6B34B34BF612D47E310073FD397D
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mx_125_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mx_125_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: F903FF39804D9804E634B2B1E0872E7B
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: F903FF39804D9804E634B2B1E0872E7B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_125_sk;../src/packs/PIC32MX570F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32
  delimiter: ''
  key: optimization-level
  security: NON_SECURE
  value: -O2
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_125_sk;../src/packs/PIC32MX570F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
