files:
- generatedChecksum: DB6E23937562973A100BC9A7DC91C99C
  logicalPath: config/pic32mk_mcj_curiosity_pro/bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB6E23937562973A100BC9A7DC91C99C
- generatedChecksum: 1CD43CF210B84CBE150E875E0E71286A
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1CD43CF210B84CBE150E875E0E71286A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F39C3968895CEC805FEE49DDEDE17C6E
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F39C3968895CEC805FEE49DDEDE17C6E
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 54C558624F0C733DCEA3AA48E96121F7
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 54C558624F0C733DCEA3AA48E96121F7
- generatedChecksum: EC7B2897D8D8DE100A38DE1269321B28
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC7B2897D8D8DE100A38DE1269321B28
- generatedChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
- generatedChecksum: 5C6769BE2DE6D43EC80B53DAEB0374E2
  logicalPath: config/pic32mk_mcj_curiosity_pro/bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C6769BE2DE6D43EC80B53DAEB0374E2
- generatedChecksum: EC210548FD5EDF4AACC2D63F74546799
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: EC210548FD5EDF4AACC2D63F74546799
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 848286252841AFE9AEEC10E0CD784605
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 848286252841AFE9AEEC10E0CD784605
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: F705CAEF2491191950FE5CDE5F54BF68
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F705CAEF2491191950FE5CDE5F54BF68
- generatedChecksum: A983FD269A9188D5D5F44742A70DEECA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: A983FD269A9188D5D5F44742A70DEECA
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: E9B9FC42D8053F798D903160C8DD2B81
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: E9B9FC42D8053F798D903160C8DD2B81
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32
  delimiter: ''
  key: optimization-level
  security: NON_SECURE
  value: -O2
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
