files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5B0ABC7040175601AE3BFF86683325BD
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B0ABC7040175601AE3BFF86683325BD
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: E1BA541FB184012E788F799A2023A039
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E1BA541FB184012E788F799A2023A039
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F39C3968895CEC805FEE49DDEDE17C6E
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F39C3968895CEC805FEE49DDEDE17C6E
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: C1722AA7BB93704CFACAFBA8D1C0B362
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1722AA7BB93704CFACAFBA8D1C0B362
- generatedChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3FD0074B778A52137F33FC2786257D32
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3FD0074B778A52137F33FC2786257D32
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: CD3AE25C52B897EC920F25E92E7A0832
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CD3AE25C52B897EC920F25E92E7A0832
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C660AC7C2F731290B24E2BBF3FB2685F
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: C660AC7C2F731290B24E2BBF3FB2685F
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: 05AE5FA71401B0C13CEDF4E47B913F34
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 05AE5FA71401B0C13CEDF4E47B913F34
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
